/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_amyas_grocery_JNIActivity */

#ifndef _Included_com_example_amyas_grocery_JNIActivity
#define _Included_com_example_amyas_grocery_JNIActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_amyas_grocery_JNIActivity
 * Method:    helloJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_amyas_grocery_JNIActivity_helloJni
  (JNIEnv *, jclass);

/*
 * Class:     com_example_amyas_grocery_JNIActivity
 * Method:    addCalc
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_amyas_grocery_JNIActivity_addCalc
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
